### ISSUE TITLE
How might one go about implementing this in a yeoman project?

### ISSUE THREAD

**Issue by aboutaaron** [rdmurphy/node-copytext#1]
I'd love to add this to our generator, but my node fu is weak.

**Comment by rdmurphy** [comment]
Woo!

There are a couple layers to getting that done. (Basing all of this on the assumption you're referring to this [generator](https://github.com/cirlabs/generator-newsapp).)
1. There needs to be a `.xlsx` file available somewhere. There's another step to the process we use in our generator I'm still breaking out. [`quaff`](https://github.com/rdmurphy/quaff) was the first part, `node-copytext` was the second – the Google Spreadsheet syncing is next. It doesn't have to be built in Google Spreadsheets though as long the `.xlsx` file adheres to the expectation of `node-copytext`. At worst, you could manually export this somewhere.
2. Y'all use `grunt` – this would probably need a `grunt` plugin intermediary to fully hook into that ecosystem because it doesn't really play along with passing data between plugins. That's in the cards. I imagine it isn't too hard to build one. It'd probably have to write the generated object to the disc as JSON for a templating library to pick up. Which leads to...
3. Your generator currently doesn't do any HTML templating, which needs to be possible to pass in the data for building. It doesn't necessarily have to be `nunjucks` (the grunt plugin you'd want is [grunt-nunjucks-2-html](https://www.npmjs.com/package/grunt-nunjucks-2-html), though!) – just something that takes in data to process for templating. You can see how we did it with our [previous generator](https://github.com/texastribune/generator-tt-newsapps/blob/master/app/templates/Gruntfile.js#L153-L166).

So! Step one on my side is to get on that `grunt` plugin. :smile:

**Comment by rdmurphy** [comment]
For the sake of documentation, #2 has been resolved by the [release of the plugin](https://github.com/rdmurphy/grunt-copytext).
